os:
  - linux
  - osx
  
language: node_js
node_js:
  - "iojs"
  - "7"

before_install:
  - npm install nativefier -g

script:
  - nativefier --name "Some Awesome App" "http://medium.com"
  - ls -lisa
