environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm install nativefier -g

test_script:
  - node --version
  - npm --version
  - nativefier --name "Some Awesome App" "http://medium.com"
  - ls -lisa
